### PR TITLE
Fixed config reference

### PR DESCRIPTION
**Pull request by monty16597**

### CODE REVIEW

**Comment by monty16597** [comment]
Review @monty16597

**Comment by monty16597** [comment]
Review @monty16597

**Comment by monty16597** [comment]
Review @monty16597

**Comment by monty16597** [comment]
Review @monty16597

**Comment by monty16597** [comment]
Review @monty16597

**Comment by monty16597** [comment]
Review @monty16597

**Comment by monty16597** [comment]
Review @monty16597

**Comment by monty16597** [comment]
Review @monty16597

**Review by alonjamohit77icloud — DISMISSED** [review]

**Comment by monty16597** [comment]
Review @alonjamohit77icloud

**Comment by monty16597** [comment]
Review require @alonjamohit77icloud

**Comment by monty16597** [comment]
Review require @alonjamohit77icloud

**Comment by monty16597** [comment]
Review require @alonjamohit77icloud

**Review by alonjamohit77icloud — APPROVED** [review]

**Pull request merged**
